sudo: required

services:
  - docker

script:
- docker build -t sfeinste/docker-all-the-things:test -f Dockerfile.test .
- docker run sfeinste/docker-all-the-things:test

after_success:
  - docker build -t sfeinste/docker-all-the-things .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sfeinste/docker-all-the-things;
    fi
