version: '3'
services:
    node-dev:
        image: node:8
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        working_dir: "/app"
        command: npm run start:dev
    node-test:
        image: node:8
        volumes:
            - .:/app
        working_dir: "/app"
        command: npm run test:watch
